### ISSUE TITLE
Client-no-log-sync test failure

### ISSUE THREAD

**Issue by nuggetwheat** [hypertable/hypertable#42]
Here's the test output:
<pre>
115/281 Testing: Client-no-log-sync
115/281 Test: Client-no-log-sync
Command: "/bin/env" "TEST_BIN_DIR=/home/doug/build/hypertable/debug/src/cc/Hypertable/Lib/" "/home/doug/src/hypertable/tests/integration/mutator-no-log-sync/run.sh" "/opt/hypertable/doug/0.9.8.6/bin"
Directory: /home/doug/build/hypertable/debug/tests/integration/mutator-no-log-sync
"Client-no-log-sync" start time: Mar 11 10:45 PDT
Output:
----------------------------------------------------------

TEST_BIN=./MutatorNoLogSyncTest
cd ${TEST_BIN_DIR};

${TEST_BIN} $@
FsBroker.local appears to be running (17218):
doug 17218 17216 0 10:43 ? 00:00:00 /opt/hypertable/doug/0.9.8.6/bin/htFsBrokerLocal --pidfile /opt/hypertable/doug/0.9.8.6/run/FsBroker.local.pid --verbose
Killing ThriftBroker.pid 17796
Killing RangeServer.pid 17599
Killing Master.pid 17409
Killing Hyperspace.pid 17297
Shutdown thrift broker complete
Shutdown range server complete
Shutdown hyperspace complete
Shutdown hypertable master complete
Removed /hypertable/servers in FS
Removed /hypertable/tables in FS
Cleared hyperspace
Shutdown FS Broker complete
FS Broker (local) Started
Hyperspace Started
Master Started
*** Load 1
Killing './htRangeServer' pid=18726
Killing './htRangeServer' pid=18827
Killing './htRangeServer' pid=18908
1426095977 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15872
1426095977 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426095977 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15870
1426095977 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426095980 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426095980 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426095980 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15870
1426095980 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426095983 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426095983 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
*** Load 2
Killing './htRangeServer' pid=19148
Killing './htRangeServer' pid=19229
Killing './htRangeServer' pid=19310
1426095989 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15870
1426095989 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426095989 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15872
1426095989 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426095992 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15870
1426095992 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426095992 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426095992 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426095995 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426095995 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
*** Load 3
Killing './htRangeServer' pid=19436
Killing './htRangeServer' pid=19517
Killing './htRangeServer' pid=19601
1426095999 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15870
1426095999 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426095999 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT from=192.168.17.12:15872
1426095999 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426096002 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15870
1426096002 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to Root RangeServer, will retry in 3000 milliseconds...
1426096002 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426096002 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426096005 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:378) Received event Event: type=DISCONNECT "COMM connect error" from=192.168.17.12:15872
1426096005 INFO MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/AsyncComm/ConnectionManager.cc:442) Disconnected: Problem connecting to RangeServer, will retry in 3000 milliseconds...
1426096010 ERROR MutatorNoLogSyncTest : (/home/doug/src/hypertable/src/cc/Hypertable/Lib/tests/MutatorNoLogSyncTest.cc:422) RangeServer on port 15871 did not come up
<end of output>
Test time =  94.17 sec
----------------------------------------------------------
Test Failed.
"Client-no-log-sync" end time: Mar 11 10:46 PDT
"Client-no-log-sync" time elapsed: 00:01:34
----------------------------------------------------------
</pre>

**Comment by nuggetwheat** [comment]
Just saw this again, load_generator was stuck here:
<pre>
Thread 1 (Thread 0x7f9ec27ad7e0 (LWP 1352)):
#0  0x000000399d80b5bc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000d2b301 in void boost::condition_variable_any::wait<boost::unique_lock<boost::mutex> >(boost::unique_lock<boost::mutex>&) ()
#2  0x0000000000e92ac6 in Hypertable::TableMutatorQueue::wait_for_buffer(boost::unique_lock<boost::mutex>&, Hypertable::ApplicationHandler**) ()
#3  0x0000000000e90c0b in Hypertable::TableMutator::wait_for_flush_completion(Hypertable::TableMutatorAsync*) ()
#4  0x0000000000e90843 in Hypertable::TableMutator::auto_flush() ()
#5  0x0000000000e90287 in Hypertable::TableMutator::set_cells(__gnu_cxx::__normal_iterator<Hypertable::Cell const*, std::vector<Hypertable::Cell, Hypertable::PageArenaAllocator<Hypertable::Cell, Hypertable::PageArena<char, Hypertable::DefaultPageAllocator> > > >, __gnu_cxx::__normal_iterator<Hypertable::Cell const*, std::vector<Hypertable::Cell, Hypertable::PageArenaAllocator<Hypertable::Cell, Hypertable::PageArena<char, Hypertable::DefaultPageAllocator> > > >) ()
#6  0x0000000000e92efd in Hypertable::TableMutator::set_cells(std::vector<Hypertable::Cell, Hypertable::PageArenaAllocator<Hypertable::Cell, Hypertable::PageArena<char, Hypertable::DefaultPageAllocator> > > const&) ()
#7  0x0000000000d1fc3f in LoadClient::set_cells(std::vector<Hypertable::Cell, Hypertable::PageArenaAllocator<Hypertable::Cell, Hypertable::PageArena<char, Hypertable::DefaultPageAllocator> > > const&) ()
#8  0x0000000000cf9285 in generate_update_load(boost::intrusive_ptr<Hypertable::Properties>&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, unsigned long, unsigned long, bool, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int, bool) ()
#9  0x0000000000cf68a0 in main ()
</pre>
